Cleanup and improve to use it in subshell, use pushd and more...

diff --git a/bin/sote b/bin/sote
--- a/bin/sote
+++ b/bin/sote
@@ -1,16 +1,16 @@
 #!/bin/bash
 ###################################
 # sote                            #
-# https://github.com/leny/sote    #
+# https://github.com/krkn/sote    #
 #                                 #
 # Copyright (c) 2014 krkn         #
 # Licensed under the MIT license. #
 ###################################
 
-SOTE_URL="https://raw.githubusercontent.com/thierrylag/sote/master/bin/sote"
+SOTE_URL="https://raw.githubusercontent.com/argael/sote/master/bin/sote"
 SOTE_PATH="$HOME/.sote/bin"
 SOTE_SCRIPT="$SOTE_PATH/sote"
-SOTE_STORE="$HOME/.sote/sote-store"
+SOTE_STORE="$HOME/.sote-store"
 
 # -----------------------------------------------------------------------------
 
@@ -21,42 +21,35 @@ if [[ ! -f "$SOTE_SCRIPT" ]]; then
     fi
 
     if [[ $(basename $0) != "sote" ]]; then
-        echo -en "\tDownloading"
+        echo -e "\tDownloading"
         curl -sS -o $SOTE_SCRIPT $SOTE_URL
     else
-        echo -en "\tLocal installation"
+        echo -e "\tLocal install"
         cp $0 $SOTE_SCRIPT
     fi
 fi
 
 # Add to profile
-for FILE in $HOME/.profile $HOME/.bash_profile $HOME/.bashrc; do
+for FILE in $HOME/.profile $HOME/.bash_profile $HOME/.bashrc $HOME/.zshrc; do
     if [[ -f $FILE ]]; then
-        if [[ $(grep -s "sote" $FILE) ]]; then
+        if [[ $(grep -s "$SOTE_PATH" $FILE) ]]; then
             unset FILE; break
         fi
     fi
 done
 
 if [[ -f $FILE ]]; then
-    echo -en "\tAdd Sote to your $FILE"
+    echo -e "\tAdd Sote to your $FILE"
     echo "source $SOTE_SCRIPT" >> $FILE
 fi
 
 # -----------------------------------------------------------------------------
-sote() {
-
-    # sote vars
-
-    local version=0.1.1
+sote() 
+{
+    local version="0.1.4"
     local store="$SOTE_STORE"
-
-    # reset colors
-
+    
     local NONE="\033[0m"
-
-    # regular colors
-
     local K="\033[0;30m"    # black
     local R="\033[0;31m"    # red
     local G="\033[0;32m"    # green
@@ -65,8 +58,6 @@ sote() {
     local M="\033[0;35m"    # magenta
     local C="\033[0;36m"    # cyan
     local W="\033[0;37m"    # white
-
-    # emphasized (bolded) colors
 
     local EMK="\033[1;30m"
     local EMR="\033[1;31m"
@@ -77,8 +68,6 @@ sote() {
     local EMC="\033[1;36m"
     local EMW="\033[1;37m"
 
-    # usage text
-
     local usage="
     ${EMY}Usage: ${W}sote ${G}[options] ${C}<name>
 
@@ -88,33 +77,26 @@ sote() {
 
         ${G}-h, --help                   ${W}Output usage information
         ${G}-v, --version                ${W}Output the version number
+        ${G}-a, --add ${B}<name> ${Y}[path]      ${W}Add the path to the store with the given name. If no path is given, use current path.
         ${G}-l, --list                   ${W}Lists the paths stored by sote.
         ${G}-s, --show ${B}<name>            ${W}Shows the path corresponding to the given name.
-        ${G}-a, --add ${B}<name> ${Y}[path]      ${W}Add the path to the store with the given name. If no path is given, use current path.
+        ${G}-p, --push ${B}<name>            ${W}Use pushd to save the current path.
         ${G}-r, --remove ${B}<name>          ${W}Remove the path stored by sote at the given name.
         ${G}-c, --clear                  ${W}Clear all the paths stored by sote. Ask for confirmation before acting.
     "
 
-    # Check for git
-
-    command -v git >/dev/null 2>&1 || { echo "${EMR}error: ${NONE}sote requires ${Y}git ${NONE}but it's not installed. Aborting." >&2; return 1; }
+    if [ ! $(which git) ]; then
+        echo "${EMR}error: ${NONE}sote requires ${Y}git ${NONE}command." >&2
+        return 1
+    fi
 
     # Check for store file
-
-    if [ ! -f $store ]
-    then
-        echo "" > $store
-    fi
+    if [ ! -f $store ]; then echo "" > $store; fi
 
     # Show help if no args
-
-    if [ $# == 0 ] ; then
-        echo -e "$usage${NONE}"
-        return;
-    fi
+    if [ $# == 0 ] ; then echo -e "$usage${NONE}"; return; fi
 
     # Commands
-
     action=$1
     name=$2
     path=$3
@@ -122,11 +104,9 @@ sote() {
     case "$action" in
         "-v"|"--version")
             echo -e "${Y}sote ${W}v$version${NONE}"
-            return;
             ;;
         "-h"|"--help")
             echo -e "$usage${NONE}"
-            return;
             ;;
         "--completion-keys")
             for i in $(git config --file $store --list) ; do
@@ -135,7 +115,6 @@ sote() {
 
                 echo "$i"
             done
-            return;
             ;;
         "--completion-options")
             echo "-v"
@@ -148,46 +127,47 @@ sote() {
             echo "--show"
             echo "-a"
             echo "--add"
+            echo "-p"
+            echo "--push"
             echo "-r"
             echo "--remove"
             echo "-c"
             echo "--clear"
-            return;
             ;;
         "-l"|"--list")
             for i in $(git config --file $store --list) ; do
-                i=${i//store./$C}
-                i=${i//=/ ${Y}› ${NONE}}
+                i=${i//store./}
+                i=${i//=/ ${Y}›${NONE} }
 
-                echo -e "$i"
+                [ -d $(echo $i | awk '{print $3}') ] \
+                    && echo -e "$C$i" \
+                    || echo -e "${R}${i} ${R}[NOT FOUND]${NONE}"
             done
-            return;
             ;;
         "-s"|"--show")
             path=$( git config --file $store --get "store.$name" )
             if [ "$path" != "" ]
             then
-                echo -e "${C}$name ${Y}› ${NONE}$path${NONE}"
+                echo -e "$path"
             else
-                echo -e "${EMR}error: ${NONE}no entry for ${C}$name${NONE}"
+                echo -e "${EMR}error: ${NONE}no entry for ${C}$name${NONE}"; exit 1
             fi
-            return;
             ;;
         "-a"|"--add")
-            if [ ! $path ]
-            then
+            if [ ! $path ]; then
                 path=$PWD
             else
-                path=$(cd $path; pwd)
+                path=$(cd "${path}"; pwd)
             fi
-            git config --file $store --replace-all "store.$name" $path
+            if [ ! $name ]; then
+                name=$(basename $path)
+            fi
+            git config --file $store --replace-all "store.$name" "$path"
             echo -e "${EMY}added: ${C}$name ${Y}› ${NONE}$path${NONE}"
-            return;
             ;;
         "-r"|"--remove")
             git config --file $store --unset-all "store.$name"
             echo -e "${EMY}removed: ${C}$name${NONE}"
-            return;
             ;;
         "-c"|"--clear")
             read -p "Are you sure you want clear all your SOTE entries [Yn] ? " -n 1 CONFIRM
@@ -195,23 +175,33 @@ sote() {
                 echo "" > $store
                 echo -e "\n${EMY}cleared${NONE}"
             fi
-            return;
+            ;;
+        "-p"|"--push")
+            path=$( git config --file $store --get "store.$name" )
+            if [ "$path" != "" ]; then 
+                pushd "$path" > /dev/null
+                if [ "$BASH_SUBSHELL$ZSH_SUBSHELL" != "0" ]; then 
+                    echo "$path"
+                fi
+            fi
             ;;
         *)
             path=$( git config --file $store --get "store.$action" )
-            if [ "$path" != "" ]
-            then
-                cd $path
+            if [ "$path" != "" ]; then 
+                cd "$path"
+                if [ "$BASH_SUBSHELL$ZSH_SUBSHELL" != "0" ]; then 
+                    echo "$path"
+                fi
             else
                 echo -e "${EMR}error: ${NONE}no entry for ${C}$action${NONE}"
             fi
-            return;
             ;;
     esac
 }
 
-_sote_complete() {
-    local word="${COMP_WORDS[COMP_CWORD]}"
+_sote_complete() 
+{
+    local word=$( echo ${COMP_WORDS[COMP_CWORD]} | tr "[:upper:]" "[:lower:]")
 
     if [ "$COMP_CWORD" -eq 1 ]
     then
@@ -226,7 +216,7 @@ _sote_complete() {
         if [ "$COMP_CWORD" -eq 2 ]
         then
             case "$action" in
-                "-s"|"--show"|"-r"|"--remove"|"-a"|"--add")
+                "-s"|"--show"|"-r"|"--remove"|"-a"|"--add"|"-p"|"--push")
                     COMPREPLY=( $(compgen -o nospace -W "$(sote --completion-keys)" -- "$word") )
                     ;;
                 *)
@@ -244,4 +234,4 @@ _sote_complete() {
     fi
 }
 
-complete -F _sote_complete sote
+type complete 1>/dev/null && {complete -F _sote_complete sote; }
